---
- name: Configurar IPv6 en Loopback33
  hosts: routers
  gather_facts: no

  tasks:
    - name: Asignar direccionamiento a Loopback33
      ios_config:
        lines:
          - ipv6 address 3001:ABCD:ABCD:1::1/128
          - ipv6 address FE80::1 link-local
        parents: interface Loopback33